In [1]:
import torch
import numpy as np

### Tensor Initialization

Directly from data

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

From a NumPy array

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
x_np

tensor([[1, 2],
        [3, 4]])

From another tensor

In [6]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9943, 0.3271],
        [0.5766, 0.8375]]) 



With random or constant values

In [ ]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)