In [1]:
import torch
import numpy as np

### Tensor Initialization

Directly from data

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

From a NumPy array

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
x_np

tensor([[1, 2],
        [3, 4]])

From another tensor

In [6]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9943, 0.3271],
        [0.5766, 0.8375]]) 



With random or constant values

In [7]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [8]:
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0635, 0.8711, 0.6910],
        [0.0104, 0.6135, 0.4839]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


Tensor Attributes

In [9]:
tensor = torch.rand(6, 10)

In [11]:
tensor

tensor([[0.5323, 0.3214, 0.2772, 0.5060, 0.1940, 0.7310, 0.8024, 0.2913, 0.5381,
         0.4004],
        [0.8020, 0.6985, 0.2989, 0.1658, 0.1722, 0.6567, 0.5508, 0.4601, 0.2219,
         0.4533],
        [0.8848, 0.6048, 0.3543, 0.2801, 0.1007, 0.9090, 0.9187, 0.5948, 0.2742,
         0.0085],
        [0.8045, 0.0835, 0.3319, 0.7547, 0.7608, 0.6010, 0.5272, 0.7656, 0.7039,
         0.8530],
        [0.4118, 0.9329, 0.8924, 0.9778, 0.9769, 0.7409, 0.1187, 0.4623, 0.3778,
         0.9884],
        [0.6934, 0.3964, 0.1213, 0.1455, 0.0326, 0.6641, 0.6431, 0.5754, 0.1296,
         0.2145]])

In [10]:
print(f"Shape of Tensor: {tensor.shape}")
print(f"Datatype of Tensor: {tensor.dtype}")
print(f"Device Tensor is stored on: {tensor.device}")

Shape of Tensor: torch.Size([6, 10])
Datatype of Tensor: torch.float32
Device Tensor is stored on: cpu


In [13]:
tensor = torch.ones(5, 5)
tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [14]:

tensor[:, 1] = 0

In [15]:
print(tensor)

tensor([[1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.]])


In [16]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)

In [17]:
t1

tensor([[1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1.]])

In [18]:
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor} \n")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.]]) 



In [19]:
print(tensor, "\n")
tensor.add_(6)
print(tensor)

tensor([[1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.]]) 

tensor([[7., 6., 7., 7., 7.],
        [7., 6., 7., 7., 7.],
        [7., 6., 7., 7., 7.],
        [7., 6., 7., 7., 7.],
        [7., 6., 7., 7., 7.]])


In [20]:
t = torch.ones(4)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1.])
n: [1. 1. 1. 1.]


In [21]:
t.add_(2)

tensor([3., 3., 3., 3.])

In [ ]:
from matplotlib.pylab import f


print(f"t: {t}")
print(f"n: {n}")